### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by Coelhomatias** [D3vl0per/Valorant-watcher#17]
just got this error:

(node:1970) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at Promise.then (/home/pi/Valorant-watcher/node_modules/puppeteer-core/lib/LifecycleWatcher.js:142:21)
  -- ASYNC --
    at Frame.<anonymous> (/home/pi/Valorant-watcher/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Page.goto (/home/pi/Valorant-watcher/node_modules/puppeteer-core/lib/Page.js:672:49)
    at Page.<anonymous> (/home/pi/Valorant-watcher/node_modules/puppeteer-core/lib/helper.js:112:23)
    at viewRandomPage (/home/pi/Valorant-watcher/app.js:155:20)
(node:1970) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1970) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

running on a Raspberry Pi 3

**Comment by adagari** [comment]
https://github.com/D3vl0per/Valorant-watcher/issues/6

**Comment by Coelhomatias** [comment]
ty!!

**Comment by Coelhomatias** [comment]
Hi guys, keep getting this error, updated the node version and ran  with `node --unhandled-rejections=none app.js` but this only silent the error I guess because sometimes the bot just stops

**Comment by D3vl0per** [comment]
#19
