### ISSUE TITLE
Errors after a bit of running.

### ISSUE THREAD

**Issue by parentless** [D3vl0per/Valorant-watcher#31]
After a bit of the valorant-watcher running and it going through a few streams, this error will pop up.

(node:18808) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at Promise.then (/root/valorant/node_modules/puppeteer-core/lib/LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (/root/valorant/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Page.goto (/root/valorant/node_modules/puppeteer-core/lib/Page.js:672:49)
    at Page.<anonymous> (/root/valorant/node_modules/puppeteer-core/lib/helper.js:112:23)
    at viewRandomPage (/root/valorant/app.js:175:20)
    at <anonymous>
(node:18808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by D3vl0per** [comment]
#19
