### ISSUE TITLE
Valorant watcher throwing errors

### ISSUE THREAD

**Issue by cybr-dev** [D3vl0per/Valorant-watcher#42]
Hey im getting this error,

🔗 Streamer:  https://www.twitch.tv/winghaven
(node:2828) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at Promise.then (/home/pi/Valorant-watcher/node_modules/puppeteer-core/lib/LifecycleWatcher.js:142:21)
  -- ASYNC --
    at Frame.<anonymous> (/home/pi/Valorant-watcher/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Page.goto (/home/pi/Valorant-watcher/node_modules/puppeteer-core/lib/Page.js:672:49)
    at Page.<anonymous> (/home/pi/Valorant-watcher/node_modules/puppeteer-core/lib/helper.js:112:23)
    at viewRandomPage (/home/pi/Valorant-watcher/app.js:175:20)
(node:2828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by D3vl0per** [comment]
#19 #41
